
/**
 * Contains all the valid analysis type values used in the database
 */
export const VALID_ANALYSIS_TYPES = [
  "Normal", "Scalping", "Smart", "SMC", "ICT", "Turtle Soup", "Gann", "Waves", "Patterns", 
  "Price Action", "Fibonacci", "Fibonacci Advanced", "Neural Networks", "RNN", "Time Clustering", 
  "Multi Variance", "Composite Candlestick", "Behavioral Analysis", "Daily"
] as const;

export type ValidAnalysisType = typeof VALID_ANALYSIS_TYPES[number];

/**
 * Maps analysis type keys to their valid database enum values
 */
export const analysisTypeMap: Record<string, ValidAnalysisType> = {
  // English mappings
  "scalping": "Scalping",
  "smc": "SMC",
  "ict": "ICT",
  "turtlesoup": "Turtle Soup",
  "turtle soup": "Turtle Soup",
  "turtle_soup": "Turtle Soup",
  "turtle": "Turtle Soup",
  "gann": "Gann",
  "waves": "Waves",
  "patterns": "Patterns",
  "pattern": "Patterns",
  "priceaction": "Price Action",
  "price action": "Price Action",
  "price_action": "Price Action",
  "neural_networks": "Neural Networks",
  "neural networks": "Neural Networks",
  "neuralnetworks": "Neural Networks",
  "rnn": "RNN",
  "recurrent neural networks": "RNN",
  "recurrent_neural_networks": "RNN",
  "time_clustering": "Time Clustering",
  "time clustering": "Time Clustering",
  "timeclustering": "Time Clustering",
  "multi_variance": "Multi Variance",
  "multi variance": "Multi Variance",
  "multivariance": "Multi Variance",
  "composite_candlestick": "Composite Candlestick",
  "composite candlestick": "Composite Candlestick",
  "compositecandlestick": "Composite Candlestick",
  "behavioral": "Behavioral Analysis",
  "behavioral analysis": "Behavioral Analysis",
  "behavioralanalysis": "Behavioral Analysis",
  "fibonacci": "Fibonacci",
  "fibonacci_advanced": "Fibonacci Advanced",
  "fibonacci advanced": "Fibonacci Advanced",
  "advancedfibonacci": "Fibonacci Advanced",
  "fibonacciadvanced": "Fibonacci Advanced",
  "smart": "Smart",
  "daily": "Daily",
  "normal": "Normal",
  "ICT": "ICT",
  "SMC": "SMC",
  "Turtle Soup": "Turtle Soup",
  "Gann": "Gann",
  "Waves": "Waves",
  "Patterns": "Patterns",
  "Price Action": "Price Action",
  "Scalping": "Scalping",
  "Fibonacci": "Fibonacci",
  "Fibonacci Advanced": "Fibonacci Advanced",
  "Neural Networks": "Neural Networks",
  "RNN": "RNN",
  "Time Clustering": "Time Clustering",
  "Multi Variance": "Multi Variance",
  "Composite Candlestick": "Composite Candlestick",
  "Behavioral Analysis": "Behavioral Analysis",
  
  // Arabic mappings
  "مضاربة": "Scalping", 
  "سكالبينج": "Scalping",
  "نظرية هيكل السوق": "SMC",
  "نظريةهيكلالسوق": "SMC",
  "نظرية السوق": "ICT",
  "نظريةالسوق": "ICT",
  "الحساء السلحفائي": "Turtle Soup",
  "الحساءالسلحفائي": "Turtle Soup",
  "جان": "Gann",
  "تقلبات": "Waves",
  "نمطي": "Patterns",
  "حركة السعر": "Price Action",
  "حركةالسعر": "Price Action",
  "ذكي": "Smart",
  "عادي": "Normal",
  "يومي": "Daily",
  "شبكات عصبية": "Neural Networks",
  "شبكاتعصبية": "Neural Networks",
  "شبكات عصبية متكررة": "RNN",
  "شبكاتعصبيةمتكررة": "RNN",
  "تصفيق زمني": "Time Clustering",
  "تصفيقزمني": "Time Clustering",
  "تباين متعدد العوامل": "Multi Variance",
  "تباينمتعددالعوامل": "Multi Variance",
  "شمعات مركبة": "Composite Candlestick",
  "شمعاتمركبة": "Composite Candlestick",
  "تحليل سلوكي": "Behavioral Analysis",
  "تحليلسلوكي": "Behavioral Analysis",
  "فيبوناتشي": "Fibonacci",
  "تحليل فيبوناتشي متقدم": "Fibonacci Advanced",
  "تحليلفيبوناتشيمتقدم": "Fibonacci Advanced"
};
