
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nhvkviofvefwbvditgxo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5odmt2aW9mdmVmd2J2ZGl0Z3hvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU2MzQ4MTcsImV4cCI6MjA1MTIxMDgxN30.TFOufP4Cg5A0Hev_2GNUbRFSW4GRxWzC1RKBYwFxB3U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

/**
 * Ensures that the user has a valid session.
 * Returns true if the session is valid, false otherwise.
 */
export const ensureValidSession = async (): Promise<boolean> => {
  try {
    // Check if there's a current session
    const { data: { session }, error } = await supabase.auth.getSession();
    
    if (error) {
      console.error('فشل في التحقق من الجلسة:', error);
      return false;
    }
    
    if (!session) {
      console.log('لا توجد جلسة نشطة');
      return false;
    }
    
    // Check if the session is expired
    const now = Math.floor(Date.now() / 1000);
    if (session.expires_at && session.expires_at < now) {
      console.log('انتهت صلاحية الجلسة، محاولة تحديثها');
      
      // Try to refresh the session
      const { data, error: refreshError } = await supabase.auth.refreshSession();
      
      if (refreshError) {
        console.error('فشل في تحديث الجلسة:', refreshError);
        return false;
      }
      
      return !!data.session;
    }
    
    return true;
  } catch (e) {
    console.error('خطأ غير متوقع في التحقق من صلاحية الجلسة:', e);
    return false;
  }
};
