
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nhvkviofvefwbvditgxo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5odmt2aW9mdmVmd2J2ZGl0Z3hvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU2MzQ4MTcsImV4cCI6MjA1MTIxMDgxN30.TFOufP4Cg5A0Hev_2GNUbRFSW4GRxWzC1RKBYwFxB3U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      storage: typeof window !== 'undefined' ? window.localStorage : undefined
    },
    global: {
      headers: {
        'x-application-name': 'chart-analyzer'
      }
    },
    realtime: {
      params: {
        eventsPerSecond: 10
      }
    }
  }
);

// وظيفة مساعدة للتحقق من صلاحية جلسة المصادقة وتحديثها إذا لزم الأمر
export const ensureValidSession = async (): Promise<boolean> => {
  try {
    const { data: sessionData } = await supabase.auth.getSession();
    const session = sessionData?.session;
    
    if (!session) {
      console.log('لا توجد جلسة متاحة، يجب تسجيل الدخول');
      return false;
    }
    
    // التحقق من صلاحية الجلسة
    if (session.expires_at) {
      const expiresAt = new Date(session.expires_at * 1000);
      const now = new Date();
      const buffer = 60 * 1000; // دقيقة واحدة من الوقت الإضافي
      
      if (expiresAt.getTime() - now.getTime() < buffer) {
        console.log('جلسة المصادقة على وشك الانتهاء، جاري التحديث');
        const { data, error } = await supabase.auth.refreshSession();
        
        if (error) {
          console.error('فشل في تحديث جلسة المصادقة', error);
          return false;
        }
        
        console.log('تم تحديث جلسة المصادقة بنجاح');
        return !!data.session;
      }
    }
    
    return true;
  } catch (err) {
    console.error('خطأ أثناء التحقق من صلاحية الجلسة:', err);
    return false;
  }
};
